/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExerciseTailwindIndexRouteImport } from './routes/exercise/tailwind/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseTailwindIndexRoute = ExerciseTailwindIndexRouteImport.update({
  id: '/exercise/tailwind/',
  path: '/exercise/tailwind/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercise/tailwind/': typeof ExerciseTailwindIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercise/tailwind': typeof ExerciseTailwindIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercise/tailwind/': typeof ExerciseTailwindIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exercise/tailwind/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exercise/tailwind'
  id: '__root__' | '/' | '/exercise/tailwind/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExerciseTailwindIndexRoute: typeof ExerciseTailwindIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise/tailwind/': {
      id: '/exercise/tailwind/'
      path: '/exercise/tailwind'
      fullPath: '/exercise/tailwind/'
      preLoaderRoute: typeof ExerciseTailwindIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExerciseTailwindIndexRoute: ExerciseTailwindIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
